#!/usr/bin/env bash
# Job name
##SBATCH --reservation=bigotj_136 
#SBATCH -J HDF5
# Asking for one node
#SBATCH -N 1
#SBATCH -n 16
# Standard output
#SBATCH -o slurm.sh%j.out
# Standard error
#SBATCH -e slurm.sh%j.err

echo "=====my job information ===="
echo "Node List: " $SLURM_NODELIST
echo "my jobID: " $SLURM_JOB_ID
echo "Partition: " $SLURM_JOB_PARTITION
echo "submit directory:" $SLURM_SUBMIT_DIR
echo "submit host:" $SLURM_SUBMIT_HOST
echo "In the directory:" $PWD
echo "As the user:" $USER

module purge
module load gcc/11.2.0/gcc-4.8.5
module load hdf5/1.12.0/gcc-11.2.0-openmpi

srun -n 4 ./phdf5_ex2

